# Generated by Django 4.2.1 on 2023-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0008_auto_20210618_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, default='*****', max_length=20, verbose_name='کدملی'),
        ),
    ]
